services:
  niqurl-server:
    container_name: niqurl-server
    build:
        context: ../../
        dockerfile: ./build/server/local/Dockerfile
    links:
      - redis
    networks:
      - default
    command: ./server
    environment:
      - name=value
  niqurl-cli:
    container_name: niqurl-cli
    build:
      context: ../../
      dockerfile: ./build/cli/local/Dockerfile
    links:
      - redis
      - niqurl-server
    networks:
      - default
    stdin_open: true 
    tty: true
    command: ./niqurl
  redis:
    container_name: niqurl-redis
    build:
      context: ../../
      dockerfile: ./build/redis/Dockerfile
    networks:
      - default
networks:
  default:
    driver: bridge
