services:
  niqurl-server:
    container_name: niqurl-server
    env_file: ../../config/niqurlconfigs/envfile.env
    build:
        context: ../../
        dockerfile: ./build/server/local/Dockerfile
    links:
      - redis
    networks:
      - default
    ports:
      - "127.0.0.1:${SERVER_PORT}:${SERVER_PORT}"
    command: /niqurl/cmd/server/server
    stdin_open: true 
    tty: true
  niqurl-cli:
    container_name: niqurl-cli
    build:
      context: ../../
      dockerfile: ./build/cli/local/Dockerfile
    links:
      - redis
      - niqurl-server
    networks:
      - default
    stdin_open: true 
    tty: true
  redis:
    container_name: niqurl-redis
    image: redis
    networks:
      - default
networks:
  default:
    driver: bridge
