services:
  niqurl-server:
    container_name: niqurl-server
    build:
        context: ../../
        dockerfile: ./build/server/local/Dockerfile
    links:
      - redis
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - default
  niqurl-cli:
    container_name: niqurl-cli
    build:
      context: ../../
      dockerfile: ./build/cli/local/Dockerfile
    links:
      - redis
      - niqurl-server
    networks:
      - default
    stdin_open: true 
    tty: true        
  redis:
    container_name: niqurl-redis
    image: redis
    networks:
      - default
networks:
  default:
    driver: bridge